blacklists:
  EFNet:
    address: rbl.efnet.org
    type: A
    # Legal placeholders: %player% for player name, %bl% for the name of the DNS blacklist
    on-match: ban %player% Your address was found in a DNS blacklist for open proxies!
  DroneBL:
    address: dnsbl.dronebl.org
    type: A
    on-match: ban %player% Your address is listed in the %bl% DNS Blacklist.